lucametehau/CloverEngine

- makefile
- search.h
- thread.h
- uci.h
Also when aspiration window passes 700, don't make it INF.
```
ELO   | 3.45 +- 4.05 (95%)
SPRT  | 10.0+0.10s Threads=1 Hash=8MB
LLR   | 2.95 (-2.94, 2.94) [0.00, 5.00]
```
> Don't consider improving when in check

- makefile
- search.h
- uci.h
preparing to remove eval when in check
> no futility pruning when in check

- evaluate.h
- makefile
- search.h
- tune.h
- uci.h
second step to remove evaluating in check
> don't eval when in check

- evaluate.h
- makefile
- tune.h
- uci.h
```
ELO   | 15.48 +- 8.01 (95%)
SPRT  | 8.0+0.08s Threads=1 Hash=8MB
LLR   | 2.95 (-2.94, 2.94) [-1.00, 4.00]
Games | N: 3144 W: 754 L: 614 D: 1776
```
> scale depending on number of pawns of strong side remaining

- net.h
Hello,
I found this project and built it recently, but due to the recent addition of a call to `memcpy` in net.h, I needed to include an extra header to that file. Just a small edit in case anyone else has the same problem.
> Added missing header declaration

- search.h
> reduce less for captures with good history

- makefile
- movepick.h
- search.h
- thread.h
> Index nodes searched by move type and use it for noisy move ordering as well

- makefile
- search.h
> Ttmove negative see

- defs.h
- evaluate.h
- history.h
- makefile
- move.h
- movepick.h
- net.h
- search.h
- tune.h
Bench: 2646238
New net architecture:
4x768-2x768-1
Gave an additional 20 elo, yes it's low, but it's elo
> 4buckets net

- makefile
- thread.h
> Tuned movepicker values for more

- src/makefile
- src/search.h
> Less lmr if node is pv

- src/makefile
- src/search.h
- src/thread.h
> avoid extending far in the game tree(one of the main causes of stack overflow)

- src/evaluate.h
- src/makefile
- src/search.h
> Remove tempo, as evaluation isn't symmetrical anymore

- src/makefile
- src/search.h
> Negative extension

- src/makefile
- src/net.h
> 2% speedup

- src/history.h
- src/makefile
- src/uci.h
> Change history formula

- src/makefile
- src/net.h
- src/search.h
- src/thread.h
> Futility pruning for captures

- src/makefile
- src/search.h
> More pruning depth if improving

- src/search.h
> Weird idea i got from testing some puzzles

- src/makefile
- src/search.h
> Negative extension when ttValue less than alpha

- src/makefile
- src/search.h
> Reduce less if pv node

- src/makefile
> New net branch

- src/makefile
- src/net.h
> Increase input quantization coefficient

- src/makefile
- src/search.h
> Do singular extension only for cut and pv nodes

- src/incbin.h
- src/makefile
* some other fixes
* thx @crippa for noticing
Bench: 3458523
> Compile fixes

- src/makefile
- src/search.h
> Limit qsearch to only 3 moves

- src/defs.h
- src/makefile
- src/move.h
- src/movepick.h
- src/net.h
- src/uci.h
> Cleanup move gen and faster move picker

- src/makefile
- src/net.h
> Should be finally able to run fine on mac

- src/makefile
- src/search.h
> Remove nmp depth guard

- src/makefile
- src/search.h
> Lower depth guard, remove ischeck condition

- src/defs.h
- src/makefile
> Limit search depth to 100

- src/makefile
- src/search.h
> Reduce quiets if ttmove is noisy

- src/makefile
- src/search.h
- src/thread.h
- src/uci.h
> Fix previous idea and cleanup

- src/makefile
- src/search.h
> Fix improving reductions

- src/evaluate.h
- src/makefile
> Simplify pawns on 1 flank term

- src/makefile
- src/search.h
> Fix small bug in LMR, where if we had R=1, we would research anyway

- src/evaluate.h
- src/makefile
> Tweak eval scale

- src/defs.h
- src/init.h
- src/makefile
- src/move.h
> Fix FRC mode

- src/defs.h
- src/makefile
- src/search.h
Model generated on 15k Clover games at 5s+0.05s tc. Thanks a lot to @cosmobobak for running the model!
Bench: 3474718
> Normalize score, so that 100cp is 50% win, also add wdl reporting

- src/board.h
- src/makefile
- src/search.h
* credit to Stockfish for the speculative part
Bench: 3427240
> Speculative prefetch as early as possible

- src/defs.h
- src/history.h
- src/makefile
- src/thread.h
- src/uci.h
> Fit history into int16

- src/makefile
- src/search.h
> Nmp and Singular Extension tweaks

- src/board.h
- src/defs.h
- src/main.cpp
- src/makefile
- src/net.h
- src/search.h
- src/thread.h
- src/tt.h
- src/uci.h
> Major cleanups, at the suggestion of Twipply

- src/makefile
- src/movepick.h
Sad, but it seems to lose elo now.
> Remove nodes searched from move ordering

- src/makefile
- src/tt.h
- src/uci.h
> Faster tt init when threads are available

- src/makefile
- src/search.h
- src/tt.h
- src/uci.h
> Entries that were or are PV are important, so do not reduce them

- src/makefile
- src/uci.h
Trained on additional 80mil data, generated with moveloop pruning disabled for PV nodes.
> Trinity network

- src/makefile
- src/search.h
- src/uci.h
> Fix ponder ending too early

- src/defs.h
- src/history.h
- src/makefile
- src/movepick.h
- src/search.h
- src/thread.h
- src/uci.h
Threats now include the attacks from all pieces.
Use threats in history, indicating if from or to square are threatened.
> Threat History

- src/history.h
- src/makefile
- src/search.h
- src/thread.h
> Add continuation history from 4 plies ago to history usage in search

- src/makefile
- src/search.h
- src/thread.h
- src/uci.h
> Don't check timeouts in qsearch

- src/attacks.h
- src/board.h
- src/defs.h
- src/evaluate.h
- src/generate.h
- src/history.h
- src/init.h
- src/main.cpp
- src/makefile
- src/move.h
- src/movepick.h
- src/net.h
- src/params.h
- src/perft.h
- src/search.h
- src/thread.h
- src/uci.h
> Massive cleanup, change a bit LMR table for tuning

- README.md
- Fix ratings leaderboards' broken links
> Fix broken links in documentation

- src/board.h
- src/history.h
- src/init.h
- src/makefile
- src/move.h
- src/search.h
Credits to Martin, he buzzed me with this, while also being one of the first to try this
> Material correction history

- src/history.h
- src/makefile
- src/search.h
Try to maintain same average as before
> Introduce continuation correction history

- src/makefile
- src/params.h
- src/search.h
> Slightly decrease SNMP margin if our eval is improving after the last move

- src/datagen/generate.h
- src/main.cpp
- src/uci.h
> Handle CTRL+C in datagen and also get rid of #ifdefs

- src/makefile
- trained on 20k nodes data only (was neutral with master net)
- add 100 more sbs of retrain, now retraining with LinearWDL from 0.5 to 0.6
> New network
